### ISSUE TITLE
All genes filtered out when genesFilter = F in newINSPEcT()

### ISSUE THREAD

**Issue by raysinensis** [ste-depo/INSPEcT#26]
Hi, running in nonascent mode, I encountered:
``` 
matureInspObj<-newINSPEcT(tpts=tpts,
  labeling_time=NULL,
  nascentExpressions=NULL,
  matureExpressions=matExp_DESeq2,
  genesFilter = F)
```
throws many warnings and filters out all genes

seems to be due to lines about ix2/3/4 here?
```
ix1 <- apply(rpkms_total_exons==0, 1, all)
ix2 <- apply(rpkms_total_exons_variances, 1, all)
ix3 <- apply(rpkms_total_introns, 1, all)
ix4 <- apply(rpkms_total_introns_variances, 1, all)
```

**Comment by ste-depo** [comment]
Hi,
it should be fixed now (commit 421f5ce). Ar you reported, those lines contained the error, basically ix2/3/4 they lacked the comparison "==0"
Best,
Stefano
